size(200);
pair O=(0,0);
draw(O--E,Arrow);
draw(O--NE,Arrow);
draw(O--N,Arrow);
draw(O--NW,Arrow);
draw(O--W,Arrow);
draw(O--SW,Arrow);
draw(O--S,Arrow);
draw(O--SE,Arrow);
label("$E$",E,E);
label("$N$",N,N);
label("$W$",W,W);
label("$S$",S,S);
label("$NE$",position=NE,align=NE);  
