#!/bin/sh
xelatex main
asy main
xelatex main
# makeindex main
iconv -f utf-8 -t gbk main.idx | cctmkind -C mixed -s cct.ist| iconv -f gbk -t utf-8 > main.ind
bibtex main
xelatex main
xelatex main
mv main.pdf AsymptoteByExample.pdf
